// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glpqxpdbjcpfqdaizxcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdscHF4cGRiamNwZnFkYWl6eGNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMzU0NDgsImV4cCI6MjA1NTgxMTQ0OH0.WyeUxyG_H-mqpnQGdjlhyPVSl6VyFemJadf30H6dHFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);